version: '3.8'

services:
  lm-backend-api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lm-backend-api
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    environment:
      - DB_HOST=lm-backend-db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - lm-monorepo-net

  lm-backend-nginx:
    image: nginx:stable
    container_name: lm-backend-nginx
    ports:
      - "8010:80"
    volumes:
      - ./html:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lm-backend-api
    networks:
      - lm-monorepo-net

  lm-backend-db:
    image: mariadb:10.7
    container_name: lm-backend-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lm-monorepo-net

volumes:
  db_data:

networks:
  lm-monorepo-net:
    external: true
